#!/bin/bash
#
# This script is run whenever `vagrant destroy` is used to destroy
# the virtual machine. To customize this behavior, include a file
# in your local basebox/config/homebin directory: vagrant_destroy_custom
#
# Look for a custom trigger file. If this exists, we'll assume that
# all trigger actions should be handled by this custom script. If
# it does not exist, then we'll handle some basic tasks.
if [[ -f /home/vagrant/bin/vagrant_destroy_custom ]]; then
	vagrant_destroy_custom
else
	rm -rf /srv/www/default/database-admin
	rm -rf /srv/www/default/memcached-admin
	rm -rf /srv/www/default/opcache-status
	rm -rf /srv/www/default/webgrind
	rm -rf /srv/www/wp-cli
	rm -rf /srv/www/passanger.txt
	db_backup
fi
